name: Build

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [Win32, x64]
        config: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: ${{ matrix.arch == 'x64' && 'amd64' || 'x86' }}

    - name: Generate build files
      run: |
        cmake -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DSAMPGDK_ARCH=${{ matrix.arch == 'x64' && '64' || '32' }} -B build -S .
    - name: Build
      run: cmake --build build

    - name: Package
      run: cpack --config build/CPackConfig.cmake -B package

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: streamer-${{ matrix.arch }}-${{ matrix.config }}
        path: package/*.zip

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [i386, x86_64]
        config: [Debug, Release]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      run: |
        cd docker
        ARCH=${{ matrix.arch == 'x86_64' && '64' || '32' }} \
        CONFIG=${{ matrix.config == 'Debug' && 'Debug' || 'MinSizeRel' }} \
        ./build.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: streamer-linux-${{ matrix.arch }}-${{ matrix.config }}
        path: docker/build/package/*.tar.gz
